apiVersion: v2
name: keycloak-kafka-event-listener
description: A Helm chart for Keycloak with Kafka Event Listener plugin
type: application
version: 0.0.2
appVersion: "26.3.1"
home: https://github.com/scriptonbasestar/sb-keycloak-exts
sources:
  - https://github.com/scriptonbasestar/sb-keycloak-exts
maintainers:
  - name: ScriptonBaseStar
    email: scriptonbasestar@gmail.com
keywords:
  - keycloak
  - kafka
  - event-listener
  - authentication
  - identity
  - sso
annotations:
  category: Identity and Access Management
dependencies:
  - name: cloudnative-pg
    version: 0.23.x
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled
    alias: postgresql
  - name: strimzi-kafka-operator
    version: 0.45.x
    repository: https://strimzi.io/charts
    condition: kafka.enabled
    alias: kafka